"""Chatbot v9 — sub-screen TRANS dispatch
================================================================

The v1…v8 bots were structurally incomplete: when the user walked a UI splice
(opened Terms / TCD / Quality / Notes / etc.) we recorded the splice but
NEVER fired that sub-screen's TRANS task. The sub-screen owns its own SP
chain that writes to its own child tables; those tables were silently
orphaned at commit time.

v9 closes that gap.

CONTRACT
--------
For every UI splice the user has walked, IF the user has provided ANY slot
that the sub-screen owns AND a main-commit write fires this turn, THEN v9
prepends a sub-screen TRANS firing to `trans_sequence_v4` BEFORE the main
commit, mirroring Ramco's real commit topology:

    Real UI:   user clicks Terms link → fills sub-form → Save (Terms TRANS)
               → Back → fills main → Save (Main TRANS)
    v9 bot:    [POCRTTRMTRAN, POCRTMAINSBT]   (both in trans_sequence_v4)

The sub-screen TRANS choice (Save vs Approve variant) follows the main
commit's intent: a "create-and-approve" main commit pairs with each
sub-screen's Approve TRANS; a plain "create" main commit pairs with the
Save TRANS.

ZERO REGRESSION
---------------
If no UI splice was walked, or no sub-screen-relevant slot was provided,
v9 falls back to v8 behaviour exactly — same trans_sequence_v4, same
response, same state. The dispatch is additive.

WHAT v9 CHANGES (vs v8)
-----------------------
  - Prepends sub-screen write entries to `trans_sequence_v4`
  - Augments the post-commit response wording to list the sub-screen commits
  - Records `subscreen_commits_fired` in state for trace + idempotency
  - Surfaces tables-written per sub-screen for trace fidelity

WHAT v9 DOES NOT CHANGE
-----------------------
  - LLM prompts, journey classification, slot extraction
  - Splice detection (UI + data)
  - Main-commit TRANS picker
  - Validation, post-commit context, change-language detection
  - Step captions, mandatory progress
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
from typing import Any

CHATBOT = Path(__file__).resolve().parent
sys.path.insert(0, str(CHATBOT))

from bot_v8 import ChatbotV8
from bot_v2 import UI_SPLICES
from bot_v1 import REVERSE_MAP, ACTIVITY_NAME_MAP
sys.path.insert(0, str(CHATBOT.parent / "eval" / "runner"))
from metrics import BotTurnOutput


# ── Load the catalog-derived sub-screen commit map ─────────────────────────
# Generated by composer/c08_subscreen_commit_map.py
_AUDIT = CHATBOT.parent / "out" / "audit" / "subscreen_commits.json"
if _AUDIT.exists():
    SUBSCREEN_DISPATCH: dict[str, dict] = json.loads(_AUDIT.read_text())
else:
    SUBSCREEN_DISPATCH = {}


# ── Splice key → (activity_camel, screen_camel) ────────────────────────────
# Built from UI_SPLICES so the bot's splice vocabulary stays in sync with v2.
SPLICE_TO_SCREEN: dict[str, tuple[str, str]] = {
    splice_key: ("PoCrt", info["screen"])  # all current UI splices are PoCrt
    for splice_key, info in UI_SPLICES.items()
}


# ── Splice key → slot-vocabulary subset ────────────────────────────────────
# A sub-screen TRANS only fires if the user provided at least one of these
# slots; that proves the splice was substantive, not just navigational.
# Canonical slot vocabulary owned by each splice. Used to INFER that a splice
# was walked when the LLM forgets to flag `ui_splice_requested`. Kept narrow
# (only slot names that unambiguously belong to the sub-screen) so we don't
# misclassify main-screen slots as splice evidence.
SPLICE_OWNED_SLOTS: dict[str, set[str]] = {
    "terms":    {"payment_terms", "incoterm"},
    "tcd":      {"tcd_details"},
    "pr_cov":   {"pr_coverage"},
    "so_cov":   {"so_coverage"},
    "schedule": {"need_date", "schedule_type", "receipt_at"},
    "quality":  {"quality_attributes"},
    "notes":    {"notes_text"},
    "dropship": {"dropship_id"},
    "budget":   {"budget_id"},
}


# ── Mapping splice_walked ID (terms_via_LNK3, …) → splice key (terms, …) ───
SPLICE_ID_TO_KEY: dict[str, str] = {
    info["id"]: splice_key for splice_key, info in UI_SPLICES.items()
}


# ── Approve-mode detection on the main-commit task name ────────────────────
# Mirrors v2's commit_kind == "submit_and_approve" routing.
_APPROVE_TASKS = {
    "POCRTMAINTRN4",   # PoCrt: Create & Approve
    "POAMNDTRN3",      # PoAmnd: Amend & Approve   (placeholder, if added)
}


def _is_approve_task(task: str | None) -> bool:
    return bool(task) and task.upper() in _APPROVE_TASKS


class ChatbotV9(ChatbotV8):
    """v8 + sub-screen TRANS dispatch."""

    def reset(self) -> None:
        super().reset()
        # Track which splices have already had their sub-screen TRANS fired
        # this conversation, so we don't double-fire across turns.
        self.state["subscreen_commits_fired"] = []

    def respond(self, user_input: str, turn_no: int) -> BotTurnOutput:
        # Clear per-turn dispatch marker so trace reflects only THIS turn.
        self.state["_subscreen_dispatched_this_turn"] = []
        out = super().respond(user_input, turn_no)

        # ── Deterministic splice inference ────────────────────────────────
        # The LLM is occasionally inconsistent about flagging
        # `ui_splice_requested` — but if a sub-screen-owned slot has a
        # value, the user OBVIOUSLY walked the splice. Sync splice_walked
        # to the slot evidence so v9's dispatch is robust to LLM noise.
        self._infer_walked_splices_from_slots(out)

        # Did a main-commit write fire this turn? v7 stamps `_last_fired_this_turn`
        last_fired = self.state.get("_last_fired_this_turn")
        if not last_fired or last_fired.get("kind") != "write":
            return out  # nothing to dispatch alongside

        sub_commits = self._dispatch_subscreen_commits(
            main_task=last_fired.get("task"),
            journey=self.state.get("journey_locked"),
        )
        if not sub_commits:
            return out

        # Prepend sub-screen commits to trans_sequence_v4 — they conceptually
        # fired BEFORE the main commit (matching Ramco's real UI topology).
        v4 = list(getattr(out, "trans_sequence_v4", None) or [])
        sub_v4 = [
            {
                "task": s["task"],
                "kind": "write",
                "activity": s["activity"],
                "subscreen": s["screen"],
                "via_splice": s["splice_key"],
                "tables_written": s["tables_written"],
            }
            for s in sub_commits
        ]
        out.trans_sequence_v4 = sub_v4 + v4

        # Surface in trace state too
        already_fired = set(self.state.get("subscreen_commits_fired", []))
        for s in sub_commits:
            already_fired.add(s["splice_id"])
        self.state["subscreen_commits_fired"] = sorted(already_fired)
        self.state["_subscreen_dispatched_this_turn"] = sub_commits

        # Augment confirmation wording
        out.response_text = self._augmented_response(out.response_text, sub_commits)

        return out

    # ── Deterministic splice inference ─────────────────────────────────────
    def _infer_walked_splices_from_slots(self, out: BotTurnOutput) -> None:
        """If a sub-screen-owned slot has a value in state, treat the splice
        as walked (idempotent — only appends if missing). This makes v9
        resilient to LLM splice-detection misses."""
        slots = self.state.get("slots", {}) or {}
        slot_keys = {k for k, v in slots.items() if v not in (None, "", "?")}
        walked = set(self.state.get("splice_walked", []) or [])

        for splice_key, owned in SPLICE_OWNED_SLOTS.items():
            if not (owned & slot_keys):
                continue
            sid = UI_SPLICES.get(splice_key, {}).get("id")
            if sid and sid not in walked:
                walked.add(sid)
                # Also extend out.splice_walked so the trace shows it
                if sid not in out.splice_walked:
                    out.splice_walked.append(sid)

        self.state["splice_walked"] = list(walked)

    # ── Dispatch logic ──────────────────────────────────────────────────────
    def _dispatch_subscreen_commits(self, main_task: str | None,
                                    journey: str | None) -> list[dict]:
        """Return the list of sub-screen TRANS firings that should accompany
        this turn's main commit. Empty list = nothing to dispatch."""
        if not journey:
            return []

        activity_dispatch = SUBSCREEN_DISPATCH.get(journey, {})
        if not activity_dispatch:
            return []

        approve_mode = _is_approve_task(main_task)
        walked = self.state.get("splice_walked", []) or []
        already_fired = set(self.state.get("subscreen_commits_fired", []))

        firings: list[dict] = []
        for sid in walked:
            if sid in already_fired:
                continue
            splice_key = SPLICE_ID_TO_KEY.get(sid)
            if not splice_key:
                continue

            scr_info = activity_dispatch.get(self._screen_for_splice(splice_key, journey))
            if not scr_info:
                continue  # splice maps to a screen with no orphan TRANS (budget, dropship)

            # Trust splice_walked: if user (or our inference) said the splice
            # was opened, fire its TRANS. The catalog SPs have IF-branches
            # that no-op when their inputs are absent, so firing without
            # data is safe — same behaviour as Ramco's real backend.

            task_info = self._pick_task(scr_info, approve_mode)
            if not task_info:
                continue

            firings.append({
                "splice_id":      sid,
                "splice_key":     splice_key,
                "screen":         self._screen_for_splice(splice_key, journey),
                "activity":       journey,
                "task":           task_info["task"],
                "tables_written": task_info["tables"],
                "mode":           "approve" if approve_mode else "save",
            })
        return firings

    @staticmethod
    def _screen_for_splice(splice_key: str, journey: str) -> str:
        """Resolve splice key → sub-screen camel name within the activity.
        UI_SPLICES is PoCrt-specific today; if the journey is different we
        still use the same screen mapping since the same splice keys are
        reused conceptually (Terms → <Activity>Trm etc.)."""
        # PoCrt mapping is authoritative; future journeys can override here.
        return UI_SPLICES[splice_key]["screen"]

    @staticmethod
    def _pick_task(screen_dispatch: dict, approve_mode: bool) -> dict | None:
        """Pick save vs approve variant, with sensible fallback."""
        save = screen_dispatch.get("save")
        apr = screen_dispatch.get("approve")
        if approve_mode and apr:
            return apr
        if save:
            return save
        return apr  # last-resort fallback

    @staticmethod
    def _augmented_response(base: str, sub_commits: list[dict]) -> str:
        if not sub_commits:
            return base
        parts = [f"{s['screen']} via {s['task']}" for s in sub_commits]
        if len(parts) == 1:
            extra = parts[0]
        elif len(parts) == 2:
            extra = " and ".join(parts)
        else:
            extra = ", ".join(parts[:-1]) + f", and {parts[-1]}"
        addendum = f"Sub-screen commits also fired: {extra}."
        return (base + "\n\n" + addendum) if base else addendum


if __name__ == "__main__":
    bot = ChatbotV9()
    bot.reset()
    print("v9 smoke:")
    for i, msg in enumerate([
        "Create a PO for SUP-300 in USD with NET30 payment terms and a 5% TCD discount, today, BUY-5, ITM-12 100 units at 5.",
        "Save it as draft.",
    ], 1):
        out = bot.respond(msg, i)
        v4 = getattr(out, "trans_sequence_v4", None) or []
        fired = [s["task"] for s in v4] or ([out.trans_invoked] if out.trans_invoked else [])
        print(f"\nT{i}: fired={fired}")
        for s in v4:
            if s.get("subscreen"):
                print(f"   ↳ {s['subscreen']:<14} writes {s.get('tables_written',[])}")
        print(f"   response: {(out.response_text or '')[:200]}")
